### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FlipperKitNetworkPlugin - react native 0.63.2

### ISSUE THREAD

**Issue by rebekahshaw92** [react-native-community/upgrade-support#105]
## Environment

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 66.44 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_45 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

React Native 0.63.2

## Description

I am creating an app using react native. I updated my project from react native 0.60 to react native 0.63.2. In doing this I had to update my cocoapods within my iOS project.

When I try to run my app on an iOS emulator in Xcode I get the following errors.

![Screenshot 2020-09-01 at 12 23 44](https://user-images.githubusercontent.com/6704278/92225814-b0192180-ee9b-11ea-9440-051ffcf0c57c.png)

![Screenshot 2020-09-01 at 12 40 15](https://user-images.githubusercontent.com/6704278/92225829-b4ddd580-ee9b-11ea-89b3-29e249463a23.png)

**Comment by nicholascm** [comment]
@rebekahshaw92 Check this post out: https://github.com/react-native-community/upgrade-support/issues/90 - I was able to solve this exact issue by following the instructions there in xCode - seems to be a valid solution.

**Comment by TianShun2018** [comment]
同样的问题，求救
