### ISSUE TITLE
updating 0.62.2 to 0.63.4 project.pbxproj issues

### ISSUE THREAD

**Issue by ThinkSalat** [react-native-community/upgrade-support#136]
## Environment

System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 467.06 MB / 16.00 GB
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Things I’ve done to figure out my issue

- [ x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

## Upgrading version

0.63.4

## Description

When running the upgrade, hardly any of the files actually worked. And for some reason, there's a lot of mismatching stuff in the project.pbxproj file. I am using this [god forsaken tool](https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.4) to manually go through and update these files (how is it that react native has gotten _harder_ to update than before?), and for a lot of the lines in "before" version of the file, I can't delete the line because the number doesn't match. 

How is this app actually working if this file already doesn't have the right stuff in it? Like, it is very different from the before version in the upgrader, and I _just_ upgraded to 0.62.2. How do I appraoch this ridiculous task? I've been at it for hours now.

**Comment by karladler** [comment]
Some of the plugins you may have installed before probably wrote in some of the files, this changes of cause the line numbers. That's probably also why auto update failed. I had success by searching the parts directly before or after the changes and then matching it with the changes. But tbh. it's quite time consuming.
Also downloading the new file from the tool and use "select for compare" & "compare with selected" functionaliyt from VScode is very helpful here.

**Comment by ThinkSalat** [comment]
Turns out that I didn't have to go line by line to fix the project.pbxproj, I did the upgrade and changed the other files and it worked! Really ridiculous that the upgrade tool doesn't mention that you shouldn't change the project.pbxproj file

**Comment by quicksilverr** [comment]
@ThinkSalat  Can you please explain this part "I did the upgrade" ?

**Comment by JDMathew** [comment]
@ThinkSalat, for the most part not changing the project.pbxproj should just work, however it might be worth noting that with some react native version changes there may be changes to the project.pbxproj that could be needed.

**Comment by evangrim** [comment]
A comment as to why you don't have to update manually:

I think project.pbxproj gets updated based on other dependencies, which are updated elsewhere; for example, Pods are build based on package.json contents, and those are then updated by xcode in project.pbxproj when you build in xcode or using xcode command line tools.

If you want to see it in action, try updating a dependency, cd ios && pod install; look for changes in project.pbxproj; build for ios and look again for changes in project (I think you'll see changes after the last step, i.e. building for ios)
