### ISSUE TITLE
App crashed when remote debugger is on. (0.61.5 to 0.63.0)

### ISSUE THREAD

**Issue by mohity777** [react-native-community/upgrade-support#141]
## Environment====>

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 1.33 GB / 7.78 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-22 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Things I’ve done to figure out my issue==>

I am attaching the photo of view summary which shows up when app is crashed. I have also logcat the crash. Also there is something written on the console when i turned remote debugging-

1) In View summary report on mobile-

 https://lh3.googleusercontent.com/-uUs6J0T3Sxs/YFTimz8dbgI/AAAAAAAABZI/es0E4wZIrGwmaCqFUmWjQtMKOCsdlpH-ACK8BGAsYHg/s0/2021-03-19.jpg?authuser=0

2) In logcat-

My android project is com.polbol

on Crash logcat-

https://lh3.googleusercontent.com/-dNaocgz4FQ0/YFTkHnmDcFI/AAAAAAAABVk/I06b2NZ7qfkWW8TvmDsm4xohiGcUxpr4QCK8BGAsYHg/s0/2021-03-19.png?authuser=1

before crash logcat-

https://lh3.googleusercontent.com/-nLRkCOUakVI/YFTleJndeOI/AAAAAAAABVw/obR7dSqi98g_R8UcZJm1yAp8Ohfr1HoBgCK8BGAsYHg/s0/2021-03-19.png?authuser=1

3) On the console-

info Launching Dev Tools...
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at UnableToResolveError.buildCodeFrameMessage (D:\projects\ZZZ\polbol-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:304:17)
    at new UnableToResolveError (D:\projects\ZZZ\polbol-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (D:\projects\ZZZ\polbol-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (D:\projects\ZZZ\polbol-app\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at D:\projects\ZZZ\polbol-app\node_modules\metro\src\lib\transformHelpers.js:271:42
    at Server.<anonymous> (D:\projects\ZZZ\polbol-app\node_modules\metro\src\Server.js:842:41)
    at Generator.next (<anonymous>)

- [x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

Yes i used upgrade-helper + react native upgrade tool command

## Upgrading version
0.63.0

## Description
i just upgraded my react native project from V0.61.5 to V0.63.0. It is working fine when no debugger is on but when I turn on remote debugging it crashes. This does not used to happen earlier. Please guys  please help me out.

## Reproducible demo

 After running project i turn on debugger and app crashes

**Comment by annewanghy** [comment]
I met it too, when upgrading from 0.60.6 to 0.63.0 on mac

**Comment by mohity777** [comment]
I guess u might have also upgraded the lib for react-native-reanimated. Reanimated 2 does not support remote debugging. I switched back to prev version of reanimated and the issue was not occurring anymore.
