### ISSUE TITLE
TVEventHandler after upgrade to React Native 0.64.0

### ISSUE THREAD

**Issue by Michal-Kurzal** [react-native-community/upgrade-support#145]
## Environment

System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.19 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found

## Things I’ve done to figure out my issue

npx react-native upgrade

## Upgrading version

0.64.0

## Description

I'm working on a android TV react native Project. TvEventHandler is a very important Part of the App. Everything was fine until I try to upgrade React Native from 0.63.3 to 0.64.0. After the Upgrade I cannot import TvEventHandler as usual form 'react-native'. Import is undefined. 

## Reproducible demo

Creat new React-Native App:  npx react-native init RN64 version=0.64.0 or
react-native init RN64 version=0.64.0

Replace App.js with:

Import React, {useEffect} from 'react';
import {TVEventHandler, Text, View} from 'react-native';

function App() {
  useEffect(() => {
    console.log('TV ', TVEventHandler);
  }, []);

<End Here>

**Comment by hhaidar** [comment]
See: https://reactnative.dev/blog#moving-apple-tv-to-react-native-tvos

You need to switch to the fork: https://github.com/react-native-tvos/react-native-tvos

**Comment by Michal-Kurzal** [comment]
Thank you.
It works.
All I had to do was to run **_yarn add react-native@npm:react-native-tvos_**
