### ISSUE TITLE
Cyclic dependency in Cocoapods after upgrading from 0.63.4 -> 0.64.0

### ISSUE THREAD

**Issue by tijs** [react-native-community/upgrade-support#150]
## Environment

System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.57 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 30.0.0, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

This is the setup before upgrading. After upgrading react and react-native versions have changed of course.

## Things I’ve done to figure out my issue

- [x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.
- I have checked the issues here, in the metro and in the react-native project
- 
## Upgrading version

0.64.0

## Description

After upgrading iOS builds will fail with the following error:

```
Cycle in dependencies between targets 'AD' and 'FBReactNativeSpec'; building could produce unreliable results.
Cycle path: AD → ADIntents → BVLinearGradient → React → React-RCTAnimation → FBReactNativeSpec → AD
Cycle details:
Target build order preserved because “Parallelize Build” is off

→ Target 'AD' has create directory command with output '/Users/tijs/Library/Developer/Xcode/DerivedData/KubusApp-fdqmmsifozyckxgwovqxkqcnjqwd/Build/Products/Debug-iphonesimulator/AD.app/Frameworks'
→ Target 'ADIntents': ProcessProductPackaging  /Users/tijs/Library/Developer/Xcode/DerivedData/KubusApp-fdqmmsifozyckxgwovqxkqcnjqwd/Build/Intermediates.noindex/KubusApp.build/Debug-iphonesimulator/ADIntents.build/ADIntents.appex-Simulated.xcent
○ Target 'ADIntents' has create directory command with output '/Users/tijs/Library/Developer/Xcode/DerivedData/KubusApp-fdqmmsifozyckxgwovqxkqcnjqwd/Build/Products/Debug-iphonesimulator/ADIntents.appex'
→ Target 'BVLinearGradient' has create directory command with output '/Users/tijs/Library/Developer/Xcode/DerivedData/KubusApp-fdqmmsifozyckxgwovqxkqcnjqwd/Build/Products/Debug-iphonesimulator/BVLinearGradient/BVLinearGradient.framework/Headers'
→ Target 'React' has target dependency on Target 'React-RCTAnimation'
→ Target 'React-RCTAnimation' has target dependency on Target 'FBReactNativeSpec'
→ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
○ Target 'FBReactNativeSpec' has copy command from '/Users/tijs/projects/persgroep/popular-platform-app/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h' to '/Users/tijs/Library/Developer/Xcode/DerivedData/KubusApp-fdqmmsifozyckxgwovqxkqcnjqwd/Build/Products/Debug-iphonesimulator/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
```

My Podfile looks like this before upgrading (redacted pod list for brevity). Since our projects builds multiple targets from one codebase the Target list is large. Each target uses a Widget so it needs an Intents target as well hence the ADIntens, etc targets. This seems to be the source of the cyclic dependency. But only after upgrading to 0.64.0, in 0.63.4 this Podfile works fine.

```
source 'https://cdn.cocoapods.org'
source 'git@bitbucket.org:persgroep/ios-cocoapods-specs.git'
source 'git@bitbucket.org:persgroep/mychannels-cocoapods.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

abstract_target 'Kubus' do
  use_frameworks!

  config = use_native_modules!

   # Internal SDK's
  pod 'TemptationSDK', '~> 3.3'
  pod 'PipOidcSDK', '0.12.3'
  # etc..

  # Firebase
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'FirebaseDynamicLinks'

  pod 'FirebasePerformance', '3.3.0'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Crashlytics'
  pod 'FirebaseInstanceID'

  pod 'FMDB', :modular_headers => true
  pod 'Gifu', '~> 3.2'
  pod 'SwiftLint', '~> 0.39.1'
  pod 'FBSDKCoreKit', '7.1.1'
  
  # Native Network
  pod 'Moya', '~> 13.0'

  use_react_native!(:path => config["reactNativePath"])

  target 'AD' do
    target 'KubusAppTests' do
      inherit! :search_paths
    end
    target 'KubusNewsFramework' do
      inherit! :search_paths
    end
    target 'ADIntents' do
      inherit! :search_paths
    end
  end
  target 'PZC' do
    target 'PZCIntents' do
      inherit! :search_paths
    end
  end
  target 'DG' do
    target 'DGIntents' do
      inherit! :search_paths
    end
  end
  target 'TUB' do
    target 'TUBIntents' do
      inherit! :search_paths
    end
  end
  target 'DS' do
    target 'DSIntents' do
      inherit! :search_paths
    end
  end
  target 'BD' do
    target 'BDIntents' do
      inherit! :search_paths
    end
  end
  target 'BNDESTEM' do
    target 'BNDESTEMIntents' do
      inherit! :search_paths
    end
  end
  target 'ED' do
    target 'EDIntents' do
      inherit! :search_paths
    end
  end
  target 'HLN' do
    target 'HLNIntents' do
      inherit! :search_paths
    end
  end
  target 'SUR7' do
    target 'SUR7Intents' do
      inherit! :search_paths
    end
  end
  target 'ADUITests' do
    pod 'Nimble'
  end
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    # to avoid
    # [!] The 'Pods-ADM' target has transitive dependencies that include statically linked binaries: (FirebaseCore, FirebaseInstanceID, FirebaseDynamicLinks, and FirebaseMessaging)
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |pi|
     # workaround for running on M1 macs
    pi.pods_project.targets.each do |target|
      target.build_configurations.each do |buildconfig|
        buildconfig.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
```

After updating the react and react-native versions the only change to the Podfile is these two lines:

```
use_react_native!(:path => config[:reactNativePath],  :hermes_enabled => false)

# and..

  post_install do |pi|
     # workaround for running on M1 macs
    pi.pods_project.targets.each do |target|
      target.build_configurations.each do |buildconfig|
        buildconfig.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  # added post_install script here
    react_native_post_install(pi)
  end
```

I have tried with no changes to Podfile, clearing all node modules, clearing the lock files for npm and cocoapods. clearing the build caches and Pods dir, etc but nothing gets me past the dependency cycle issue.

**Comment by tushar-singhal** [comment]
get rid of `use_frameworks!` and it should work

**Comment by tijs** [comment]
Thanks, I’ll check if that does the trick. I do believe we still have some other dependencies that need that setting though so I’ll have to figure out a workaround for that.

**Comment by tijs** [comment]
@tushar-singhal i was not in the office for a while but, as expected, the project will not build without `use_frameworks!` As far as i know `use_modular_headers!` is not yet an option for React Native project as Folly & Glog deps for RN will not build without the `use_frameworks!` setting.

Do you know a way to use modular headers without breaking the react-native deps?

**Comment by tijs** [comment]
I managed to fix this issue by upgrading cocoa pods to the latest version. I still can't upgrade but this is now due to metro/babel issues
