### ISSUE TITLE
after upgrading with upgrade helper ios didn't work

### ISSUE THREAD

**Issue by Stringsaeed** [react-native-community/upgrade-support#17]
## Environment

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 575.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 25.0.0, 28.0.3, 29.0.2
      System Images: android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

0.62.0

## Description

i tried to upgrade first i used npx react-native upgrade but it didn't work so i go through upgrade helper tool and [this guide](https://github.com/react-native-community/upgrade-support/issues/13) but it also didn't work 
<img width="1792" alt="Screen Shot 2020-03-28 at 12 53 43 PM" src="https://user-images.githubusercontent.com/37156636/77821468-2ba7c300-70f3-11ea-9c92-256844fd2f3b.png">
here a screenshot of errors that i got

## Reproducible demo

just i upgraded

**Comment by dpyeates** [comment]
Same for me.

<img width="1347" alt="Screenshot 2020-03-28 at 15 50 36" src="https://user-images.githubusercontent.com/944670/77827147-e80d8300-710b-11ea-854c-7fa5b98fca14.png">

**Comment by tdcook** [comment]
See issue #11. There are still some manual changes needed to project.pbxproj that the guide doesn't mention.

**Comment by Stringsaeed** [comment]
@tdcook i already did and the same issue

**Comment by tindn** [comment]
It took me a while to figure this out, but you gotta add `FB_SONARKIT_ENABLED=1` to the following position

<img width="711" alt="Screen Shot 2020-03-28 at 7 49 29 PM" src="https://user-images.githubusercontent.com/7987738/77836555-89f19780-712d-11ea-81df-c68c17f5efc0.png">

Not particularly sure why this is needed. I found it by generating a new project and go through the diff of the new `project.pbxproj` against the old one.

**Comment by Stringsaeed** [comment]
@tindn I can confirm it worked, but I countered in another issue related to bridging header file,

**Comment by tindn** [comment]
@Stringsaeed can you search for this line in your project.pbxproj file?
```
DEAD_CODE_STRIPPING = NO;
```
If it's there, remove it, that should fix it the bridging header problem

**Comment by Gokaysim** [comment]
I had the same issue with @Stringsaeed . Fortunately, @tindn your suggestion solved the build time problem. But It fails at run time and logs below message

This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.

**Comment by Stringsaeed** [comment]
I had the same issue @Gokaysim, thank you @tindn removing `DEAD_CODE_STRIPPING = NO;` successfully built the project but i had this line in logs with crash `This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.`

**Comment by Stringsaeed** [comment]
got it to work by just adding an empty file in the project in Xcode [here is my reference](https://stackoverflow.com/a/55419920/9970979)

**Comment by Gokaysim** [comment]
@Stringsaeed  just add a .swift file. Even, you already added and removed it.

**Comment by tindn** [comment]
@Stringsaeed do you mean just adding "File.swift" in the project? I did but it didn't make a difference to me. Glad it worked for you

**Comment by josmithua** [comment]
Leaving the empty `.swift` file as @Gokaysim mentioned worked for me.
