### ISSUE TITLE
Changed proguard rule for Hermes is not specified in the upgrade helper for 0.62.

### ISSUE THREAD

**Issue by muclipse** [react-native-community/upgrade-support#19]
# Feature Request

The new proguard rule for using Hermes:

`-keep class com.facebook.jni.** { *; }`

is not mentioned in the upgrade helper for 0.62.

## Why it is needed

Omitting this update makes the Android release app with Hermes and Proguard crashes on startup:

```
FATAL EXCEPTION: create_react_context
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: com.facebook.jni.NativeRunnable
```

**Comment by muclipse** [comment]
In the React Native documentation of 0.61,
The Hermes setup page (https://reactnative.dev/docs/0.61/hermes) specified this Proguard rule:

`-keep class com.facebook.hermes.unicode.** { *; }`

In the documentation of 0.62 (https://reactnative.dev/docs/hermes), the Proguard rule is updated:

```
-keep class com.facebook.hermes.unicode.** { *; }
-keep class com.facebook.jni.** { *; }
```

I think this change was made because 0.62 uses Hermes 0.4.0.

However, I spent hours because this Proguard.rule change was not specified in the update helper.

If it is specified somewhere, it should be more salient for developers who are using Hermes.

**Comment by lucasbento** [comment]
I wonder how we can add this to the upgrade-helper, I was thinking that we can add an inline comment here:
![image](https://user-images.githubusercontent.com/6207220/77896911-41df8b80-7279-11ea-90e7-8755d6e25275.png)

(reason is that we can only add inline comments on diffs)

And maybe add this issue at the top with a title like "Upgrade proguard rule for Hermes".

Thoughts on this @muclipse @pvinis?

**Comment by pvinis** [comment]
Right. I checked the `proguard-rules.pro` file, and you can also see [here](https://github.com/facebook/react-native/blob/master/template/android/app/proguard-rules.pro), there is nothing in there for hermes like the docs say. I feel this change might be more suitable in the [releases changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#android-specific-2).

For now, probably the best we can do is what @lucasbento said, and we can add a comment or a note on the 0.62 upgrade helper.

**Comment by lucasbento** [comment]
> Right. I checked the proguard-rules.pro file, and you can also see here , there is nothing in there for hermes like the docs say.

Yeah, this is probably because the template does not use Hermes by default.

> I feel this change might be more suitable in the releases changelog .

Agreed, cc @alloy.

**Comment by muclipse** [comment]
> I feel this change might be more suitable in the releases changelog .

I agree, @alloy.

Also, 

> we can add a comment or a note on the 0.62 upgrade helper.
cc @pvinis 

Another good place would be adding a comment in the block comment in android/build.gradle ([file](https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle)) above:

```
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

```

**Comment by alloy** [comment]
Hmm, yeah we actually went back and forth on this in the CHANGELOG https://github.com/react-native-community/releases/pull/166#discussion_r398630351 but dropped the ball in the end.

Thanks for the reminder, added this https://github.com/react-native-community/releases/pull/182

**Comment by kelset** [comment]
Eloy's PR is now merged, I guess we can close this? :)

**Comment by lucasbento** [comment]
We still have some work to do on Upgrade-Helper side, will be done today

**Comment by lucasbento** [comment]
Added a comment to Upgrade-Helper to mention this change at react-native-community/upgrade-helper#224 and it should be up in prod in a few minutes.

Thank you so much for reporting this @muclipse, this will probably help a lot of people!

Thanks for the help here @pvinis & @alloy 🤗
