### ISSUE TITLE
Upgrade to react-native 0.62 FATAL EXCEPTION: create_react_context (android)

### ISSUE THREAD

**Issue by YahiaJabeur** [react-native-community/upgrade-support#22]
## Environment
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 60.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
## Upgrading version
 RN 0.62.0 from RN 0.61.4
## Description
I did all the steps to upgrade the android project, but when I run on android I receive this error:

```
FATAL EXCEPTION: create_react_context
java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
```
<img width="747" alt="Screen Shot 2020-03-29 at 21 50 10" src="https://user-images.githubusercontent.com/46672998/77859025-48351f80-7207-11ea-96b3-61ebc2bd3e7c.png">

any idea how to resolve it?
FYI the entry file is :    `entryFile: "index.js",`
` enableHermes: true`
I tried restart packager and removing cache

**Comment by AmirAlOmari** [comment]
Hey @YahiaJabeur 👋 Did you find the solution? 🤔

**Comment by YahiaJabeur** [comment]
@AmirAlOmari sorry I didn't find the solution, but for some reason when I repeated the upgrade steps It works fine
