### ISSUE TITLE
Update from 0.61.5 to 0.62.0 => 'folly/gen/String.h' file not found

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-community/upgrade-support#23]
Hi,
I have updated app from 0.65.1 to 0.62.0 and I got

`'folly/gen/String.h' file not found` with Flipper-Folly pod

Any suggestions how to fix it? Or what is causing it? Especially annoying on CI.

No error on clean project. 

My current workaround:

1. Add this to postinstall actions:

```
cd ios && rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install --repo-update;
```

2. Podfile:

```
# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end
```

**Comment by lorenc-tomasz** [comment]
Update done by example step by step using https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0

**Comment by lorenc-tomasz** [comment]
I have tried any method I know but without above workaroind I got:

```
ios/Pods/Headers/Private/Flipper-Folly/folly/Subprocess.h:119:10: 'folly/gen/String.h' file not found
```

**Comment by lorenc-tomasz** [comment]
It's for sure something with Pods but don't know what.

**Comment by krakz999** [comment]
Hi @lorenc-tomasz , what was the issue?

**Comment by krakz999** [comment]
I fixed it by removing "gen/" from my .gitignore that came with RN 0.62+

**Comment by lorenc-tomasz** [comment]
HI,
I did the same. I thought that this gen/ was made by mistake by someone from our team. Didn't thought that this "gen/" was from RN 0.62+

**Comment by lorenc-tomasz** [comment]
Nevertheless, it was very annoying issue that I wasn't expected to have the source in gitignore file.
