### ISSUE TITLE
Build fails React-Core

### ISSUE THREAD

**Issue by kiwavi** [react-native-community/upgrade-support#233]
Hi all, when I run on IOS I get this error below

```
The following build commands failed:
	CompileC /Users/mac/Library/Developer/Xcode/DerivedData/pum_vendor-arqoqzoncnvwefglipketrebhxvo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Core.build/Objects-normal/x86_64/RCTAppSetupUtils.o /Users/mac/projects/vendor-app/node_modules/react-native/React/AppSetup/RCTAppSetupUtils.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Core' from project 'Pods')
(1 failure)
```

On Xcode, it returns an error 'file rctappdelegate.h not found'.  

Here is my setup build:

System:
    OS: macOS 12.6.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 29.00 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.04.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

So far, I have tried removing Pods, build and reinstalling pods to no avail.

**Comment by srithar21** [comment]
I am also facing this issue in React native 0.69.5 migration, any solution?
