### ISSUE TITLE
Suggested @babel/core@7.20.0 version does not exist

### ISSUE THREAD

**Issue by bnobre** [react-native-community/upgrade-support#247]
## Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz  
    Memory: 2.42 GB / 7.88 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-223.8836.35.2231.10406996
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.20 - C:\Program Files\Microsoft\jdk-11.0.20.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Things I’ve done to figure out my issue

- [X] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

## Upgrading version

0.72.4

## Description
The following packages "@babel/core" and "babel/preset-env" do not have version 7.20.0 available for installation. And the upgrade-helper guides you to install this 7.20.0 version. That is the problem! How should I proceed?

## Reproducible demo
Run the commands below:
yarn upgrade @babel/core@7.20.0 --dev
yarn upgrade @babel/preset-env@7.20.0 --dev

**Comment by bnobre** [comment]
Sorry... The version installed is @babel/core@7.22.11 and @babel/preset-env@7.22.10

**Comment by arnoldc** [comment]
https://github.com/facebook/react-native/blob/v0.71.17/template/package.json#L17C6-L17C29
its actually confusing , its even in the template and I check the npm repo 7.20.0 is not there!
