### ISSUE TITLE
Bundles rebuilding too frequently

### ISSUE THREAD

**Issue by KishCom** [react-native-community/upgrade-support#276]
I moved from 0.71.16 to 0.73.7 and something changed so that now my dev builds pause between each navigation stack screen to (re?)download a bundle. I am using @react-navigation.
The waiting for each screen to bundle+download has slowed my development down dramatically. How do I revert back to the behavior 0.71.x was doing where it did a download of the whole bundle up front?

This has to be a tiny configuration flag I'm missing.

**Comment by Tchaikovsky1114** [comment]
Did you solved this problem? I had same issue.

**Comment by KishCom** [comment]
I didn't find a solution or even any reference in docs to what change could've caused this. I just continue to suffer load-times between screens.

**Comment by shubhamguptadream11** [comment]
We are also experincing this in our recent upgrade from 0.72.5 to 0.79.2. Any suggestions how to resolve this?
