### ISSUE TITLE
android build failing after upgrading to 0.75

### ISSUE THREAD

**Issue by ktourvas** [react-native-community/upgrade-support#286]
## Environment

System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 82.55 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-26 | Google APIs ARM 64 v8a
      - android-27 | ARM 64 v8a
      - android-27 | Google APIs ARM 64 v8a
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-28 | Google Play Intel x86 Atom
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /Users/kostas.tourvas/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: ^18.2.0
  react-native:
    installed: 0.75.1
    wanted: ^0.75.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Things I’ve done to figure out my issue

- [ ] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

## Upgrading version

0.75.1

## Description

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class android.support.v4.app.INotificationSideChannel found in modules core-1.9.0.aar -> core-1.9.0-runtime (androidx.core:core:1.9.0) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules core-1.9.0.aar -> core-1.9.0-runtime (androidx.core:core:1.9.0) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules core-1.9.0.aar -> core-1.9.0-runtime (androidx.core:core:1.9.0) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.media.MediaBrowserCompat found in modules media-1.0.0.aar -> media-1.0.0-runtime (androidx.media:media:1.0.0) and support-media-compat-26.1.0.aar -> support-media-compat-26.1.0-runtime (com.android.support:support-media-compat:26.1.0)
     Duplicate class android.support.v4.media.MediaBrowserCompat$CallbackHandler found in modules media-1.0.0.aar -> media-1.0.0-runtime (androidx.media:media:1.0.0) and support-media-compat-26.1.0.aar -> support-media-compat-26.1.0-runtime (com.android.support:support-media-compat:26.1.0)
     Duplicate class android.support.v4.media.MediaBrowserCompat$ConnectionCallback found in modules media-1.0.0.aar -> media-1.0.0-runtime (androidx.media:media:1.0.0) and support-media-compat-26.1.0.aar -> support-media-compat-26.1.0-runtime (com.android.support:support-media-compat:26.1.0)
     Duplicate class android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal found in modules media-1.0.0.aar -> media-1.0.0-runtime (androidx.media:media:1.0.0) and support-media-compat-26.1.0.aar -> support-media-compat-26.1.0-runtime (com.android.support:support-media-compat:26.1.0)

**Comment by ktourvas** [comment]
Just noticed issue not present when 
android.enableJetifier=true 
in android/gradle.properties 
is not removed as indicated by upgrade helper

**Comment by aurangs7** [comment]
Yeah, I am getting the same issue in react native version: 0.75.3

**Comment by tibbe** [comment]
Same here, if I remove `enableJetifier` as per the upgrade helper the Android build fails.

**Comment by Ajololr** [comment]
Jetifier is marked as obsolete and should not be used. https://github.com/mikehardy/jetifier

Instead, you should migrate from using the `com.android.support` libraries in your project. You can identify the support libraries either by searching or by using `Dependency Analyzer` in `Android Studio` and update them.
