### ISSUE TITLE
Upgrade RN from 0.74.2 -> 0.75.4: "Application violated contract..."

### ISSUE THREAD

**Issue by wmonecke** [react-native-community/upgrade-support#293]
## Environment

```bash
info Fetching system and libraries information...
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 119.83 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 23
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

## Things I’ve done to figure out my issue

- [x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.

## Upgrading version

0.75.4

## Description

When upgrading from 0.74.2 to 0.75.4, the app builds. However, when running it stops at the ios/[project]/main.m file.
Specifically at the `UIApplicationMain` line with the error: `Thread 1: signal SIGABRT`.

<img width="1407" alt="Screenshot 2024-10-08 at 19 52 40" src="https://github.com/user-attachments/assets/3e03370d-f496-44bc-b319-db9ac059ee4b">

If I look into UIApplicationMain I see the error:
`"Application violated contract by causing UIApplicationMain() to return. This incident will be reported."`

<img width="1412" alt="Screenshot 2024-10-08 at 19 58 22" src="https://github.com/user-attachments/assets/85516003-2931-4909-bd82-dbc6fb7b0d00">

The error is a bit non-verbose. I have cleaned pods and done the upgrade twice at this point.

Any ideas?

## Reproducible demo

Upgrade from 0.74.2 to 0.75.4

**Comment by serhiy-z-israelit-pro** [comment]
also updated from react-native 0.73.8 to 0.75.4, and finished up getting this error

**Comment by wmonecke** [comment]
@serhiy-z-israelit-pro yeah, this error is a bit vague. Not sure what ill do next. It will probably be a manual upgrade by copypasting it into a new RN project.

**Comment by g-siedlecki** [comment]
I also encountered this issue while trying to upgrade from 0.74.1 to 0.75.4. 

My app finally launched after commenting out the following line from `AppDelegate.mm`:
`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];`

Looks like this call should've been removed back in 0.71.0, but for some reason I left it out.

**Comment by divyegd** [comment]
@g-siedlecki how do you initialize bridge in this case? As it is being used by rootView:

`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                                  launchOptions:launchOptions];
        RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                         moduleName:moduleName
                                                  initialProperties:nil];`
