### ISSUE TITLE
Upgrade issue from 0.74.4 to 0.76.3 for iOS

### ISSUE THREAD

**Issue by georgi2005atanasov** [react-native-community/upgrade-support#305]
## Environment
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M3
  Memory: 5.10 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/randomuser/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/randomuser/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

## Things I’ve done to figure out my issue

-  I used upgrade-helper (https://react-native-community.github.io/upgrade-helper/) to do my upgrade.
- After using the helper i tried deleting and reinstalling cocoapods, node_modules, Podfile.lock, Podfile, yarn.lock, tried cleaning cache of everything

## Upgrading version

I am upgrading the app from 0.74.4 to 0.76.3

## Description

The problem is that when the project is built and i try to get into it two of two following things happen, depending on the device: If it is an emulator i get an error "You can't open the application 'yourApp' because this application is not supported on this mac". If it is a physical device, I get into the app, it "starts loading" the starting screen appears, but it throws me out after 10-15 seconds.

**Comment by JayCynn** [comment]
I'm having the exact same issue! Any solutions so far?

**Comment by georgi2005atanasov** [comment]
My problem
