### ISSUE TITLE
Issue with generating Release apk in React Native 0.62

### ISSUE THREAD

**Issue by Ramboaa** [react-native-community/upgrade-support#46]
Issue with generating Release apk in React Native 0.62

![error](https://user-images.githubusercontent.com/44179989/78749314-6fb68580-7987-11ea-9867-938e7344776d.PNG)

**Comment by lucasbento** [comment]
Wwe need a lot more information in order to help with this, please fill in another issue following the issue template specified at the beginning.

Also try to provide relevant code, whether or not it worked on `0.61.5` and if possible a project to reproduce the error you are experience.
