### ISSUE TITLE
What is the process of upgrading for TypeScript version from 0.61.5 to 0.62.x

### ISSUE THREAD

**Issue by neoswallow** [react-native-community/upgrade-support#48]
My repo is 0.61.5 with TypeScript template.
How can I upgrade to 0.62.2?

**Comment by lucasbento** [comment]
@emin93, @radko93: perhaps you can help with this?

**Comment by radko93** [comment]
@neoswallow you can check latest [devDependencies in package.json](https://github.com/react-native-community/react-native-template-typescript/blob/master/template/package.json#L16) of the template and see which dependencies you need to upgrade compared to your package.json. You can only see the diff from 0.61.5 to 0.62.0 [here](https://github.com/react-native-community/react-native-template-typescript/commit/76abfd1e4ca5604c000d46892bf4f6f10b28d2af#diff-ebf2741126a75bcd0ccbf8df09b0f0fd)

**Comment by neoswallow** [comment]
If I understand correctly, I go through diffs between 0.61.5 and 0.62.2 (current latest) and also check devDependencies in package.json and match versions. Am I understanding it correctly?

**Comment by radko93** [comment]
@neoswallow yes but probably only need to change `package.json`, other files are the same as in the regular upgrade helper.

**Comment by lucasbento** [comment]
Closing this as it seems to be resolved, please reopen if needed @neoswallow.

Thanks for the help, @radko93!
