### ISSUE TITLE
Library not found for -lCocoaAsyncSocket after upgrading from 0.60.5 to 0.62

### ISSUE THREAD

**Issue by YahiaJabeur** [react-native-community/upgrade-support#50]
## Environment

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 726.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

 0.62.0  from 0.61.5

## Description

Library not found for -lCocoaAsyncSocket

<img width="705" alt="Screen Shot 2020-04-10 at 16 11 05" src="https://user-images.githubusercontent.com/46672998/78996925-e6997d00-7b45-11ea-83ab-ef66e3eaba30.png">

After upgrading to rn 0.62 and doing the steps from https://react-native-community.github.io/upgrade-helper
I received this error. any idea how to fix ??

**Comment by cinder92** [comment]
@YahiaJabeur how did you fix the issue?

**Comment by YahiaJabeur** [comment]
@cinder92 
I applied this solution https://github.com/facebook/react-native/issues/28483#issuecomment-610839293

This issue contains more discussion about the error https://github.com/react-native-community/upgrade-support/issues/36

Let me know if you need more help ;)

**Comment by ketanvault** [comment]
I'm having the same issue as above. But none of the above solution worked for me.

**Comment by levitomer** [comment]
Same here..

**Comment by orazo** [comment]
got to build settings in the Project and the target and add to Library Search

$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) 
$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) 
$(inherited)

without quotes

clean build folder -> run build

**Comment by Mohammed-Alsheikh** [comment]
go to build setting -> library search path -> double click on it and add this 3 command:
 $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
  $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
   $(inherited)
    clean and rebuild

**Comment by karpinski1994** [comment]
> got to build settings in the Project and the target and add to Library Search
> 
> (TOOLCHAINDIR)/usr/lib/swift−5.0/(PLATFORM_NAME) (TOOLCHAINDIR)/usr/lib/swift/(PLATFORM_NAME) $(inherited)
> 
> without quotes
> 
> clean build folder -> run build

it doesnt work
