### ISSUE TITLE
0.62.2 -> 0.63.0-rc.0 Cannot find module node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js

### ISSUE THREAD

**Issue by palkerecsenyi** [react-native-community/upgrade-support#60]
## Environment

```
System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 343.18 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.0-rc.0 => 0.63.0-rc.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Upgrading version

0.62.2 -> 0.63.0-rc.0

## Description

I've upgraded using https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.0-rc.0, and have run `./gradlew clean`. When I run `./gradlew assembleRelease`, I get the following error during the build:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/palkerecsenyi/Documents/Projects/PalChat/node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js
'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Weirdly, the file it specifies (`/Users/palkerecsenyi/Documents/Projects/PalChat/node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js`) does indeed exist:

![image](https://user-images.githubusercontent.com/22198767/79574953-e4d93780-80b8-11ea-97a3-1591c58dddc8.png)

It has the following contents:

```js
#!/usr/bin/env node
"use strict";

require("./tools/gracefulifyFs");

var _ = require("./");

(0, _.run)();

//# sourceMappingURL=bin.js.map
```

## Reproducible demo

- Upgrade React Native from 0.62.2 -> 0.63.0-rc.0

- Upgrade Hermes from 0.4.2 -> 0.5.0

- Follow upgrade guide (https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.0-rc.0)
- Change Hermes command path:

```
project.ext.react = [
    enableHermes: true,
    hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermesc"
]
```

- Run `./gradlew clean`

- Run `./gradlew assembleRelease`

**Comment by grabbou** [comment]
Hey,

Thanks for the report. 

Does running `./assembleDebug` work for you? 
Does enabling / disabling Hermes fixes it for you?

**Comment by thymikee** [comment]
Can you clear Watchman cache just in case? Metro is run with `--reset-cache` when built from Android assemble task, so we don't need to clear that, but Watchman may feed it with wrong information (e.g. previously you had CLI hoisted to top `node_modules/` but now it's inside `node_modules/react-native/node_modules/`)

**Comment by palkerecsenyi** [comment]
@grabbou thanks for your reply! I can confirm that `assembleDebug` works perfectly, and everything works as expected.

@thymikee thanks, I just tried deleting `node_modules` and `package-lock.json`, then I ran `watchman watch-del-all`, reinstalled all the modules, and ran `./gradlew clean`, but sadly the error is still there.

**Comment by palkerecsenyi** [comment]
I can also confirm that this is not only an issue when upgrading.

I just tried reproducing the error with a blank project:

```
npx react-native init testapp --version 0.63.0-rc.0
cd testapp/android
./gradlew assembleRelease
```

And the same error occurred:
![image](https://user-images.githubusercontent.com/22198767/79902921-298f0680-840a-11ea-9fe1-f8da9516a7cc.png)

**Comment by nvdnvd00** [comment]
I met this issue, any update ?

**Comment by palkerecsenyi** [comment]
I'm guessing this has been fixed now? https://github.com/facebook/react-native/pull/28776
