### ISSUE TITLE
Android app doesn't show debugging options when RN migrated from 0.59.10 to 0.62.2 

### ISSUE THREAD

**Issue by Josh2941** [react-native-community/upgrade-support#75]
## Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.07 GB / 15.87 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 12.0.2 - /cygdrive/c/Program Files/Java/jdk-12.0.2/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

From 0.59.10 to 0.62.2 

## Description

I was having my Android app running fine on RN 0.59.10. When I migrated to RN 0.62.2 using react-native-upgrade-helper, the app looks like its running in release mode but the command used is react-native run-android. On pressing Ctrl+M no options are displayed and "rr"- refresh too is not working. Here is the warning displayed in terminal when tried to do actions like "r" and "d" from that terminal.

![rn warn](https://user-images.githubusercontent.com/34862136/82314793-efecf380-99e7-11ea-9273-2d4b61b0335e.PNG)

## Reproducible demo

1. Create a project with React Native version 0.59.10.
2. Migrate the project to React Native version 0.62.2 using react-native-upgrade-helper.
3. Run the App.
4. Try reloading the App by pressing "rr" or Try opening the debug options by pressing Ctrl+M.

**Comment by chrisbobbe** [comment]
I've never tried such a big jump in RN versions. It's more painstaking, but just from my experience, I'd recommend doing v0.60, then v0.61, etc.

That way, you can more precisely identify issues, and it'll make your app's history in version control easier to examine, since I imagine the diff between v0.59.10 and v0.62.2 is gigantic if you try to do it all at once.

**Comment by Josh2941** [comment]
I found the problem. I imported **BuildConfig** which actually doesn't require an import. Initially it will show as an error suggesting us to import but when we run the app using `react-native run-android` the error will be gone and the debug options will show up.
