### ISSUE TITLE
[0.61.5 to 0.62.2] Undefined symbol: Foundation.Date.distance(to: Foundation.Date) -> Swift.Double

### ISSUE THREAD

**Issue by tststs** [react-native-community/upgrade-support#77]
## Environment

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 873.91 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.11.0
    react-native: ^0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

0.62.2

## Description

After upgrading from `0.61.5` to `0.62.2` i get the following issues:

```Undefined symbol: Foundation.Date.distance(to: Foundation.Date) -> Swift.Double```

```Undefined symbol: (extension in Vision):__C.VNRecognizedText.boundingBox(for: Swift.Range<Swift.String.Index>) throws -> __C.VNRectangleObservation?```

```
Undefined symbols for architecture x86_64:
  "Foundation.Date.distance(to: Foundation.Date) -> Swift.Double", referenced from:
      closure #1 (Foundation.URL) -> () in docomondo.DODocumentUtilities.mergeFiles(at: Foundation.URL, to: Foundation.URL) -> (success: Swift.Bool, message: Swift.String?, error: Swift.Error?) in DODocumentUtilities-054ef8ac6d8767589ef2cbc934a3372df1c0c23804aeb9ece9a18f22424853d9.o
  "(extension in Vision):__C.VNRecognizedText.boundingBox(for: Swift.Range<Swift.String.Index>) throws -> __C.VNRectangleObservation?", referenced from:
      docomondo.DORecognizedPage.drawRecognizedTexts(with: __C.PDFDisplayBox, to: __C.CGContextRef) -> () in DORecognizedPage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Reproducible demo

Haven't been able to reproduce the issue on a new react-native 0.62.2 project

----------

I tried everything mentioned in other issues here and also everything listed as links in the upgrade helper. (https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2)

Thanks in advance

**Comment by tststs** [comment]
ok i solved the issue by adding

```LD_RUNPATH_SEARCH_PATHS = "$(inherited) $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) /usr/lib/swift @executable_path/Frameworks @loader_path/Frameworks";
```

to all of the build configurations across the project.

**Comment by ParmarJigarr** [comment]
@tststs In which file you added this ?
