### ISSUE TITLE
React/RCTBridgeModule.h module not found.

### ISSUE THREAD

**Issue by honey93** [react-native-community/upgrade-support#82]
## Environment

System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 443.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.17 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

From  0.59.9 to 0.62.2 for iOS only.

## Description

React/RCTBridgeModule.h module not found.

![image](https://user-images.githubusercontent.com/10286968/84152250-0388f880-aa82-11ea-881d-e1bdb47a3dd1.png)

I found the below solution at most of the places, but even it didn't work.
![image](https://user-images.githubusercontent.com/10286968/84152513-67abbc80-aa82-11ea-9188-8523d248a121.png)

**Comment by awinograd** [comment]
@honey93 any luck resolving this issue?

**Comment by awinograd** [comment]
Looks like this was related to my upgrade to 0.63.1 and the fact that I'm using a mono repo

`use_react_native!(:path => config["reactNativePath"])`

needs to become

`use_react_native!(:path => config[:reactNativePath])`

**Comment by luism3861** [comment]
1.- Clean (cmd+shift+K)
2.-Build core React - select React as the scheme in Xcode and build it (cmd+B)
3.-	Build the library that is failing (e.g. RCTBridge).
4.-	Build your app.

**Comment by honey93** [comment]
When I installed all the packages using cocoa pods and removed the manual linking for iOS, it got resolved.  @awinograd
