### ISSUE TITLE
After upgrade 0.62.2 to 0.63.2, build fails with LaunchScreen.xib file not found

### ISSUE THREAD

**Issue by AbhiShrek** [react-native-community/upgrade-support#99]
## Environment

System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 228.44 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

0.63.2 from 0.62.2

## Problem

I used npx react-native upgrade command to upgrade to latest (0.63.2)
The upgrade gave error for following 3 files, but succeded.
1. ios/PodFile
2. ios/MyApp/AppDelegate.m
3. ios/MyApp.xcodeproj/project.pbxproj

I fixed the PodFile and AppDelegate.m file as shown in the update-helper diff 
https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.2

But the third file i didnt change as it was told "Dont Do It"
https://github.com/react-native-community/cli/issues/652#issuecomment-525774407

Now the build fails with LauchScreen.xib file not found.
![Screenshot 2020-08-23 at 1 53 29 PM](https://user-images.githubusercontent.com/11253347/90974380-436f6000-e548-11ea-87af-b80b31a2ec48.png)

This file deleted as a part of upgrade (and LauchScreen.storyboard was added instead)
Still somehow the project is trying to read this deleted file.

## Solution

Open the project in XCode and 
1. Remove the LaunchScreen.xib file from the Project Files view on the Left of screen.
2. Right Click and add the LaunchScreen.storyboard instead.

![Screenshot 2020-08-23 at 2 10 15 PM](https://user-images.githubusercontent.com/11253347/90974626-934f2680-e54a-11ea-845f-34f3df18b0b2.png)

Compile again. It works OK.

**Comment by warrenalphonso** [comment]
God bless you.

**Comment by fturkyilmaz** [comment]
how to fixed ?

**Comment by eightshone** [comment]
> how to fixed ?

Just open the ios folder with xcode you will find a file named "LaunchScreen.xib", delete it and create a new one named "LaunchScreen.storyboard" and press the run button and it should work

**Comment by AbhiShrek** [comment]
@eightshone , you dont need to "create" new. LaunchScreen.storyboard is already there after the upgrade. Just browse and select it.

**Comment by eightshone** [comment]
@AbhiShrek in my case it wasn't (Not in xcode but if I check the folder with Atom it is there. Strange, right?) but it worked anyway

**Comment by kenaitian** [comment]
I tried all of these steps today on MacOS Monterey Version 12.4 but still "error: Build input file cannot be found: 'Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/LaunchScreeen.storyboard' (in target 'Runner' from project 'Runner')" even though those two files are there.
